version: '3.8'

networks:
    nginx_network:
    internal:

services:
    starter-kit-app:
        container_name: starter-kit-app
        working_dir: /app
        build: docker/php
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - .:/app

    starter-kit-nginx:
        image: nginx:alpine
        container_name: starter-kit-nginx
        working_dir: /app
        restart: always
        networks:
            - internal
            - nginx_network
        ports:
            - "8043:80"
        volumes:
            - .:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    starter-kit-composer:
        image: composer:latest
        container_name: starter-kit-composer
        working_dir: /app
        command: update --ignore-platform-reqs
        volumes:
            - .:/app
        restart: on-failure
        depends_on:
            - starter-kit-app
